### ISSUE TITLE
Can this tool output each doc's cluster distance to every class?

### ISSUE THREAD

**Issue by tt0059** [carrot2/carrot2#151]
We want to use carrot2 to cluster some paragraphs, because carrot2 can display class labels which I think is a cool function. However, the distance of paragraphs to every class centers is very important in our work. Can you tell me how to do this? Thank you very much!

**Comment by tt0059** [comment]
Hello？

**Comment by dweiss** [comment]
There is no explicit distance... It depends on the algorithm, but for Lingo, the cluster label containment is how documents are allocated to labels, once those labels are found. It is not how numeric clustering algorithms work. Please take a look here:

https://github.com/carrot2/carrot2/wiki/pdf/osinski-2003-lingo.pdf
http://www.cs.put.poznan.pl/dweiss/site/publications/slides/iipwm2004-dweiss-lingo.pdf

**Comment by tt0059** [comment]
Well，so can I get the probability distribution that each document belongs to each class by carrot, as this is important for my work

**Comment by dweiss** [comment]
No, you can't. I gave you the pointers as to why above.

**Comment by tt0059** [comment]
If I don‘t use Lingo，but kmeans or STC also can't do this? I note that carrot2 also support kmeans and STC.

**Comment by dweiss** [comment]
STC can't because it's a similar label-based algorithm. k-means - more likely, yes, but there is no API to do it, you'd have to take a stab at the source code to emit this information. I think you should look for an algorithm where these "distances" are more explicit - any numeric clustering algorithm will work for you here, once you convert the text into feature vectors (use the traditional approach to clustering, in other words).

**Comment by tt0059** [comment]
Thank you for your patience. I got it.
